### ISSUE TITLE
Update to new format

### ISSUE THREAD

**Issue by lauraclay** [raspberrypilearning/santa-detector#2]
- [x] cover.png
- [x] LICENCE.md
- [x] CONTRIBUTING.md
- [x] meta.yml
- [x] hardware.yml
- [x] software.yml
- [x] extras.yml
- [x] overview.md
- [x] learn.md

**Comment by bennuttall** [comment]
Cover image added, no components missing.

Looks like it has all diagrams needed but the GPIO diagram may need revising to show the pin numbers clearer

**Comment by bennuttall** [comment]
`learn.md` is missing

**Comment by bennuttall** [comment]
@clivebeale can you add a "What you will learn" file similar to https://github.com/raspberrypilearning/gpio-music-box/blob/master/learn.md

Thanks

**Comment by martinpeck** [comment]
closing, cos it's done
